/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tk1_kelompok7;

/**
 *
 * @author macproi52019
 */
public class frameDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frameDashboard.class.getName());

    /**
     * Creates new form frameDashboard
     */
    public frameDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnElok = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnHilma = new javax.swing.JButton();
        btnAfif = new javax.swing.JButton();
        btnJaan = new javax.swing.JButton();
        btnNasrul = new javax.swing.JButton();
        btnRisyad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(789, 120));

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INSTITUT TEKNOLOGI MOJOSARI");
        jLabel1.setIconTextGap(10);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu Navigasi From Mahasiswa | Pemrograman Berorientasi Objek | Kelompok 7");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk1_kelompok7/icone/icons8-close-20.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk1_kelompok7/icone/l.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(216, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnElok.setBackground(new java.awt.Color(51, 204, 255));
        btnElok.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnElok.setForeground(new java.awt.Color(255, 255, 255));
        btnElok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk1_kelompok7/icone/U.png"))); // NOI18N
        btnElok.setText("ELOK DWI WINDIARTI");
        btnElok.setIconTextGap(10);
        btnElok.addActionListener(this::btnElokActionPerformed);

        jLabel3.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 12)); // NOI18N
        jLabel3.setText("Praktikum PBO - Kelompok 7 • Institut Teknologi Mojosari ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(15, 15, 15))
        );

        btnHilma.setBackground(new java.awt.Color(51, 204, 255));
        btnHilma.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnHilma.setForeground(new java.awt.Color(255, 255, 255));
        btnHilma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk1_kelompok7/icone/U.png"))); // NOI18N
        btnHilma.setText("HILMA AYU FAIHZA");
        btnHilma.setIconTextGap(10);
        btnHilma.addActionListener(this::btnHilmaActionPerformed);

        btnAfif.setBackground(new java.awt.Color(51, 204, 255));
        btnAfif.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnAfif.setForeground(new java.awt.Color(255, 255, 255));
        btnAfif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk1_kelompok7/icone/U.png"))); // NOI18N
        btnAfif.setText("MOH AFIFUR ROHMAN");
        btnAfif.setIconTextGap(10);
        btnAfif.addActionListener(this::btnAfifActionPerformed);

        btnJaan.setBackground(new java.awt.Color(51, 204, 255));
        btnJaan.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnJaan.setForeground(new java.awt.Color(255, 255, 255));
        btnJaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk1_kelompok7/icone/U.png"))); // NOI18N
        btnJaan.setText("M. JA'AN NUR ROHMAN");
        btnJaan.setIconTextGap(10);
        btnJaan.addActionListener(this::btnJaanActionPerformed);

        btnNasrul.setBackground(new java.awt.Color(51, 204, 255));
        btnNasrul.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnNasrul.setForeground(new java.awt.Color(255, 255, 255));
        btnNasrul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk1_kelompok7/icone/U.png"))); // NOI18N
        btnNasrul.setText("M NASRUL AZIZ");
        btnNasrul.setIconTextGap(10);
        btnNasrul.addActionListener(this::btnNasrulActionPerformed);

        btnRisyad.setBackground(new java.awt.Color(51, 204, 255));
        btnRisyad.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnRisyad.setForeground(new java.awt.Color(255, 255, 255));
        btnRisyad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk1_kelompok7/icone/U.png"))); // NOI18N
        btnRisyad.setText("ACHMAD RISYAD KHADAPI");
        btnRisyad.setIconTextGap(10);
        btnRisyad.addActionListener(this::btnRisyadActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAfif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJaan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(btnElok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHilma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNasrul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRisyad, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnElok, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHilma, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNasrul, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJaan, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRisyad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAfif, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNasrulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNasrulActionPerformed
        // TODO add your handling code here:
        JframeAziz frame = new JframeAziz();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNasrulActionPerformed

    private void btnElokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElokActionPerformed
        // TODO add your handling code here:
        jframeelok frame = new jframeelok();
        frame.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnElokActionPerformed

    private void btnHilmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHilmaActionPerformed
        // TODO add your handling code here:
        framehilma frame = new framehilma();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHilmaActionPerformed

    private void btnJaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJaanActionPerformed
        // TODO add your handling code here:
        JFramejaan frame = new JFramejaan();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJaanActionPerformed

    private void btnAfifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfifActionPerformed
        // TODO add your handling code here:
        Jframeafif frame = new Jframeafif();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAfifActionPerformed

    private void btnRisyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRisyadActionPerformed
        // TODO add your handling code here:
        framerisyad frame = new framerisyad();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRisyadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frameDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfif;
    private javax.swing.JButton btnElok;
    private javax.swing.JButton btnHilma;
    private javax.swing.JButton btnJaan;
    private javax.swing.JButton btnNasrul;
    private javax.swing.JButton btnRisyad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
